# Generated by Django 3.1.6 on 2021-02-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20210208_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flights', models.ManyToManyField(to='flight.Flight')),
            ],
        ),
    ]
